export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const LOCALE_CHANGE = 'LOCALE_CHANGE';
export const LOGIN_AUTH_SUCCESS = 'LOGIN_AUTH_SUCCESS';
export const LOGIN_AUTH_FAIL = 'LOGIN_AUTH_FAIL';
export const LOGOUT_AUTH_SUCCESS = 'LOGOUT_AUTH_SUCCESS';
